//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ado
{
	public virtual DBHelper db
	{
		get;
		set;
	}

	public virtual Ado ado
	{
		get;
		set;
	}

	public virtual DbTableAttribute DbTableAttribute
	{
		get;
		set;
	}

	public virtual DbDataFieldAttribute DbDataFieldAttribute
	{
		get;
		set;
	}

	public virtual string GetTableName(Type type)
	{
		throw new System.NotImplementedException();
	}

	public virtual DbTableAttribute GetTableAttribute(Type type)
	{
		throw new System.NotImplementedException();
	}

	public virtual DbDataFieldAttribute GetFieldAttribute(PropertyInfo p)
	{
		throw new System.NotImplementedException();
	}

	public virtual DbParameter[] GetTableParameters<T>()
	{
		throw new System.NotImplementedException();
	}

	public virtual DbParameter[] GetParameters<T>(T entity)
	{
		throw new System.NotImplementedException();
	}

	public virtual DbParameter[] GetNewParameters<T>(T entity)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetReaderList<T>(DbDataReader reader)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetReaderList<T>(string sql, CommandType cmdType, DbParameter[] param)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetReaderList<T>(string sql, DbParameter[] param)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetTableList<T>(DataTable dt)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetTableList<T>(string sql, CommandType cmdType, DbParameter[] param)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<T> GetTableList<T>(string sql, DbParameter[] param)
	{
		throw new System.NotImplementedException();
	}

	public virtual DataTable GetListDataTable<T>(List<T> list)
	{
		throw new System.NotImplementedException();
	}

}

